name: mleFP1
channels:
-   conda-forge
-   bioconda
dependencies:
-   python=3.9
-   jupyterlab
-   numpy
-   pandas
-   matplotlib
-   scikit-learn
-   tqdm
-   pip
-   pip:
    -   pygame
    -   black
    -   black[jupyter]

